# Generated by Django 4.2.2 on 2023-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(default="item", max_length=100),
        ),
    ]
